@extends('layouts.user')

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Your Profile</h6>
				</div>
				<div class="card-body">
					<form>
						<div class="mb-3">
							<label for="" class="font-weight-bold small">Full Name</label>
							<div class="row">
								<div class="col">
									<input type="text" class="form-control txt-md" id="email" placeholder="Enter email"
										name="email">
								</div>
								<div class="col">
									<input type="password" class="form-control txt-md" placeholder="Enter password"
										name="pswd">
								</div>
							</div>
						</div>
						<div class="mb-3">
							<label for="" class="font-weight-bold small">Username</label>
							<div class="row">
								<div class="col">
									<input type="text" class="form-control txt-md" id="email" placeholder="Enter email"
										name="email">
								</div>
							</div>
						</div>
						<div class="mb-3">
							<label for="" class="font-weight-bold small">Phone Number</label>
							<div class="row">
								<div class="col">
									<input type="number" class="form-control txt-md" id="email" placeholder="Enter email"
										name="email">
								</div>
							</div>
						</div>
						<div class="mb-3">
							<label for="" class="font-weight-bold small">Email</label>
							<div class="row">
								<div class="col">
									<input type="number" class="form-control txt-md" id="email" placeholder="Enter email"
										name="email">
								</div>
							</div>
						</div>
						<div class="mb-3">
							<label for="" class="font-weight-bold small">Address</label>
							<div class="row">
								<div class="col">
									<input type="number" class="form-control txt-md" id="email" placeholder="Enter email"
										name="email">
								</div>
							</div>
						</div>
						<div class="mb-3">
							<label for="" class="font-weight-bold small">Password</label>
							<div class="row">
								<div class="col">
									<a href="#" class="btn btn-primary btn-icon-split shadow">
										<span class="icon txt-sm text-white-50">
											<i class="fas fa-key"></i>
										</span>
										<span class="txt-sm text">Change Password</span>
									</a>
								</div>
							</div>
						</div>
						<div class="custom-control custom-checkbox pt-4">
							<input type="checkbox" class="custom-control-input" id="customCheck" name="example1">
							<label class="custom-control-label" for="customCheck">Trading Earning being shared on Platform</label>
						</div>
						<div class="row mt-5">
							<a href="#" class="btn btn-primary btn-icon-split shadow ml-auto">
								<span class="icon txt-sm text-white-50">
									<i class="fas fa-check-double"></i>
								</span>
								<span class="txt-sm text">Save Changes</span>
							</a>
						</div>
					</form>
				</div>
			</div>
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Two-Factor Security Option</h6>
				</div>
				<div class="card-body">
					<p class="small font-weight-light">Two-factor authentication is a method for protection your web account. When it is activated you need to enter not only your password, but also a special code. You can receive this code by in mobile app. Even if third person will find your password, then cant access with that code.</p>
					<div class="badge badge-info mb-3 small p-2 rounded-lg">DISABLED</div>
					<p class="mb-2 txt-md">
						1. Install an authentication app on your device. Any app that supports the Time-based One-Time Password (TOTP) protocol should work.
					</p>
					<p class="mb-2 txt-md">
						2. Use the authenticator app to scan the barcode below.
					</p>
					<p class="mb-2 txt-md">
						3. Enter the code generated by the authenticator app.
					</p>
					<a href="#" class="btn btn-primary btn-icon-split shadow ml-auto">
						<span class="icon txt-sm text-white-50">
							<i class="fas fa-check-double"></i>
						</span>
						<span class="txt-sm text">Enable 2fa</span>
					</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card bg-light text-black shadow mb-3">
				<div class="card-body text-center">
					<p class="font-weight-bold">Account Photo</p>
					<div class="text-black-50 small ">We recommend you use a square logo with dimensions 70px by 70px for best results on the checkout form.</div>
					<img class="img-profile rounded-circle col-3 mt-4" src="../assets/img/undraw_profile.svg">
					<div class="mt-4">
						<button class="small btn-sm btn btn-outline-primary">Choose Media</button>
					</div>
					<div class="row mt-5">
						<a href="#" class="btn btn-primary btn-icon-split shadow ml-auto">
							<span class="icon txt-sm text-white-50">
								<i class="fas fa-check-double"></i>
							</span>
							<span class="txt-sm text">Save Changes</span>
						</a>
					</div>
				</div>
			</div>
			<div class="card bg-light text-black shadow mb-3">
				<div class="card-body text-center">
					<p class="font-weight-bold">Identity verification</p>
					<div class="text-black-50 small ">Upload an Identity Document, for example, Driver Licence, Voters Card, International Passport, National ID.</div>
					<div class="mt-4">
						<button class="small btn-sm btn btn-outline-primary">Select Document</button>
					</div>
					<div class="row mt-5">
						<a href="#" class="btn btn-primary btn-icon-split shadow ml-auto">
							<span class="icon txt-sm text-white-50">
								<i class="fas fa-check-double"></i>
							</span>
							<span class="txt-sm text">Upload</span>
						</a>
					</div>
				</div>
			</div>
			<div class="card bg-light text-black shadow mb-3">
				<div class="card-body text-center">
					<p class="font-weight-bold">Delete Account</p>
					<div class="text-black-50 small ">Closing this account means you will no longer be able to access this account on Krypto Investment</div>
					<div class="row mt-5">
						<a href="#" class="btn btn-primary btn-icon-split shadow ml-auto">
							<span class="icon txt-sm text-white-50">
								<i class="fas fa-trash"></i>
							</span>
							<span class="txt-sm text">Delete Account</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection